language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-phaser-gamejam' ]; then cd .. && eval "mv $currentfolder generator-phaser-gamejam" && cd generator-phaser-gamejam; fi

